### ISSUE TITLE
请问Frida是哪个版本的?我用的最新的12.11.6版本好像不太行

### ISSUE THREAD

**Issue by ghost** [monkeylord/XposedFridaBridge#2]
最大的问题还是那个XposedBridge.hookMethodNative和 XposedBridge.invokeOriginalMethodNative，老是出一些问题，测试模块是对话框取消，设备7.0，

![QQ截图20200803101321](https://user-images.githubusercontent.com/27600008/89139671-0a0f8a00-d572-11ea-8a6d-97023e7ecc2d.png)

**Comment by ghost** [comment]
还有在10上，直接报找不到Lde/robv/android/xposed/XposedBridge;

![QQ截图20200803102503](https://user-images.githubusercontent.com/27600008/89140286-c7e74800-d573-11ea-959d-92b778eb8cf3.png)
经测试，是将该模块注入模块自身遇到的

**Comment by monkeylord** [comment]
> 最大的问题还是那个XposedBridge.hookMethodNative和 XposedBridge.invokeOriginalMethodNative，老是出一些问题，测试模块是对话框取消，设备7.0，
> 
> ![QQ截图20200803101321](https://user-images.githubusercontent.com/27600008/89139671-0a0f8a00-d572-11ea-8a6d-97023e7ecc2d.png)

这个BUG在最近刚修复，试试看最新的js

10的问题，能提供更详细的日志么？

**Comment by ghost** [comment]
> > 最大的问题还是那个XposedBridge.hookMethodNative和 XposedBridge.invokeOriginalMethodNative，老是出一些问题，测试模块是对话框取消，设备7.0，
> > ![QQ截图20200803101321](https://user-images.githubusercontent.com/27600008/89139671-0a0f8a00-d572-11ea-8a6d-97023e7ecc2d.png)
> 
> 这个BUG在最近刚修复，试试看最新的js
> 
> 10的问题，能提供更详细的日志么？

好的，我先试试

10的问题好像是将模块注入模块自身(为了让模块显示已激活)导致的，跟系统好像没啥关系，在7.0系统上也可以复现

**Comment by monkeylord** [comment]
> 好的，我先试试
> 
> 10的问题好像是将模块注入模块自身(为了让模块显示已激活)导致的，跟系统好像没啥关系，在7.0系统上也可以复现

有可能，和Xposed使用隔离的ClassLoader来加载模块不同，XposedFridaBridge目前使用应用自己的ClassLoader来加载，这很可能导致被加载的相同的类发生冲突。
这个我需要实验一下。

**Comment by monkeylord** [comment]
试试看最新的js？

**Comment by ghost** [comment]
嗯，问题都没有了，牛逼，不过在测试时又出现了新的问题，不过好像不是脚本的问题，是frida自身的bug
![QQ截图20200806182544](https://user-images.githubusercontent.com/27600008/89521711-93dd8280-d812-11ea-9dca-5e376e14d4cf.png)
Hook的是对话框取消的检测激活函数
![QQ截图20200806182855](https://user-images.githubusercontent.com/27600008/89521776-b7083200-d812-11ea-9a31-9c45ee9e4c0c.png)

**Comment by monkeylord** [comment]
> 嗯，问题都没有了，牛逼，不过在测试时又出现了新的问题，不过好像不是脚本的问题，是frida自身的bug
> ![QQ截图20200806182544](https://user-images.githubusercontent.com/27600008/89521711-93dd8280-d812-11ea-9dca-5e376e14d4cf.png)
> Hook的是对话框取消的检测激活函数
> ![QQ截图20200806182855](https://user-images.githubusercontent.com/27600008/89521776-b7083200-d812-11ea-9a31-9c45ee9e4c0c.png)

是Frida的问题，不过给他修复了
试试最新的JS？

**Comment by ghost** [comment]
Ok，已搞定，赞赞
