### ISSUE TITLE
android5.0 没有成功啊

### ISSUE THREAD

**Issue by vampire135** [monkeylord/XposedFridaBridge#3]
执行 frida -U com.example.flutterapp -l .\XposedFridaBridge.js   错误信息如下：

[XposedFridaBridge] Start Loading Xposed
[XposedFridaBridge] Current Application:  com.example.flutterapp
[XposedFridaBridge] Current Application Classloader:  dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.flutterapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.flutterapp-1/lib/arm, /vendor/lib, /system/lib]]]
Error: java.lang.IllegalArgumentException: Optimized data directory /data/local/tmp is not owned by the current user. Shared storage cannot protect your application from code injection attacks.
    at frida/node_modules/frida-java/lib/env.js:222
    at input:1
    at frida/node_modules/frida-java/lib/class-factory.js:200
    at FrameworkInit (repl1.js:253)
    at [anon] (repl1.js:350)
    at frida/node_modules/frida-java/lib/vm.js:39
    at frida/node_modules/frida-java/index.js:363
    at repl1.js:357

请问下，这怎么解决？

**Comment by monkeylord** [comment]
加载的问题，我在测试用新的方法

目前你可以在249行增加以下代码
~~~javascript
    var app = ActivityThread.currentApplication()
    Java.classFactory.cacheDir = "/data/data/" + app.getPackageName() + "/cache"
    Java.classFactory.codeCacheDir = "/data/data/" + app.getPackageName() + "/code_cache"
~~~

**Comment by monkeylord** [comment]
OK，现在用最新的应该也行了。

**Comment by vampire135** [comment]
出现新的问题：

XposedBridge.jar Path: /data/local/tmp/XposedBridge.jar
modules.list Path: /data/local/tmp/conf/modules.list
[XposedFridaBridge] Start Loading Xposed
[XposedFridaBridge] Current Application:  com.example.flutterapp
[XposedFridaBridge] Current Application Classloader:  dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.flutterapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.flutterapp-1/lib/arm, /vendor/lib, /system/lib]]]
TypeError: cannot read property 'get' of undefined
    at [anon] (duk_hobject_props.c:2385)
    at FrameworkInit (repl1.js:259)
    at [anon] (repl1.js:351)
    at frida/node_modules/frida-java/lib/vm.js:39
    at frida/node_modules/frida-java/index.js:363
    at repl1.js:358

**Comment by monkeylord** [comment]
有趣的问题
这个报错就是说Java.ClassFactory是undefined了，就是涉及frida的问题了，我不确定如何发生的。

你能够正常使用其他的frida插件么？
frida和frida-server的版本如何？
测试设备如何？

**Comment by monkeylord** [comment]
已确认该问题是frida-server版本问题
原因是Java.ClassFactory是近期更新的功能，旧版的frida-server中不包含该API
可以使用最新的frida-server解决
