### ISSUE TITLE
使用失败

### ISSUE THREAD

**Issue by coffeehb** [monkeylord/XposedFridaBridge#4]
环境：Nexus 5X
Android 8.1.0
使用了几个APP测试都报错类似下面这样的：
```

[XposedFridaBridge] Start Loading Xposed
[XposedFridaBridge] Current Application:  com.sankuai.meituan.dispatch.homebrew
[XposedFridaBridge] Current Application Classloader:  dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.sankuai.meituan.dispatch.homebrew-8OPVfVgdkiF4h_VzAJFMdg==/base.apk"],nativeLibraryDirectories=[/data/app/com.sankuai.meituan.dispatch.homebrew-8OPVfVgdkiF4h_VzAJFMdg==/lib/arm, /data/app/com.sankuai.meituan.dispatch.homebrew-8OPVfVgdkiF4h_VzAJFMdg==/base.apk!/lib/armeabi, /system/lib, /vendor/lib]]]
TypeError: cannot read property 'get' of undefined
    at [anon] (../../../frida-gum/bindings/gumjs/duktape.c:56618)
    at FrameworkInit (/XposedFridaBridge.js:283)
    at /XposedFridaBridge.js:375
    at frida/node_modules/frida-java-bridge/lib/vm.js:11
    at frida/node_modules/frida-java-bridge/index.js:366
    at /XposedFridaBridge.js:382
[Nexus 5X::com.sankuai.meituan.dispatch.homebrew]->
```

**Comment by monkeylord** [comment]
明白了，是高版本安卓的路径问题
修复中

**Comment by monkeylord** [comment]
应该修复了，再试试？

**Comment by coffeehb** [comment]
更新了还是这样的呢？？是我姿势不对吗？
```
[XposedFridaBridge] Start Loading Xposed
[XposedFridaBridge] Current Application:  com.alibaba.aliyun
[XposedFridaBridge] Current Application Classloader:  android.taobao.atlas.runtime.DelegateClassLoader[DexPathList[[directory "."],nativeLibraryDirectories=[/system/lib, /vendor/lib]]]
[XposedFridaBridge] Code Cache Directory:  /data/user/0/com.alibaba.aliyun/code_cache
TypeError: cannot read property 'get' of undefined
    at [anon] (../../../frida-gum/bindings/gumjs/duktape.c:56618)
    at FrameworkInit (/XposedFridaBridge.js:286)
    at /XposedFridaBridge.js:378
    at frida/node_modules/frida-java-bridge/lib/vm.js:11
    at frida/node_modules/frida-java-bridge/index.js:366
    at /XposedFridaBridge.js:385
[Nexus 5X::com.alibaba.aliyun]->
```
环境：
frida                         12.9.4
frida-tools                   7.2.2
frida-server     12.8.0

**Comment by monkeylord** [comment]
> 更新了还是这样的呢？？是我姿势不对吗？
> 
> ```
> [XposedFridaBridge] Start Loading Xposed
> [XposedFridaBridge] Current Application:  com.alibaba.aliyun
> [XposedFridaBridge] Current Application Classloader:  android.taobao.atlas.runtime.DelegateClassLoader[DexPathList[[directory "."],nativeLibraryDirectories=[/system/lib, /vendor/lib]]]
> [XposedFridaBridge] Code Cache Directory:  /data/user/0/com.alibaba.aliyun/code_cache
> TypeError: cannot read property 'get' of undefined
>     at [anon] (../../../frida-gum/bindings/gumjs/duktape.c:56618)
>     at FrameworkInit (/XposedFridaBridge.js:286)
>     at /XposedFridaBridge.js:378
>     at frida/node_modules/frida-java-bridge/lib/vm.js:11
>     at frida/node_modules/frida-java-bridge/index.js:366
>     at /XposedFridaBridge.js:385
> [Nexus 5X::com.alibaba.aliyun]->
> ```
> 
> 环境：
> frida 12.9.4
> frida-tools 7.2.2
> frida-server 12.8.0

我测试了一下，很不幸，确实是frida-server版本所致。
因为我使用到了`Java.ClassFactory`，它或许是较新版本才有的。
最新版本的frida-server是可以的，但是12.8.0我的也会报同样的错。

**Comment by coffeehb** [comment]
> > 更新了还是这样的呢？？是我姿势不对吗？
> > ```
> > [XposedFridaBridge] Start Loading Xposed
> > [XposedFridaBridge] Current Application:  com.alibaba.aliyun
> > [XposedFridaBridge] Current Application Classloader:  android.taobao.atlas.runtime.DelegateClassLoader[DexPathList[[directory "."],nativeLibraryDirectories=[/system/lib, /vendor/lib]]]
> > [XposedFridaBridge] Code Cache Directory:  /data/user/0/com.alibaba.aliyun/code_cache
> > TypeError: cannot read property 'get' of undefined
> >     at [anon] (../../../frida-gum/bindings/gumjs/duktape.c:56618)
> >     at FrameworkInit (/XposedFridaBridge.js:286)
> >     at /XposedFridaBridge.js:378
> >     at frida/node_modules/frida-java-bridge/lib/vm.js:11
> >     at frida/node_modules/frida-java-bridge/index.js:366
> >     at /XposedFridaBridge.js:385
> > [Nexus 5X::com.alibaba.aliyun]->
> > ```
> > 
> > 
> > 环境：
> > frida 12.9.4
> > frida-tools 7.2.2
> > frida-server 12.8.0
> 
> 我测试了一下，很不幸，确实是frida-server版本所致。
> 因为我使用到了`Java.ClassFactory`，它或许是较新版本才有的。
> 最新版本的frida-server是可以的，但是12.8.0我的也会报同样的错。

好的，多谢大佬。我回头用新版本的frida-server试一试。
